/**
 * Stainless SDK + Claude Code identity headers — v2-native, ported from
 * vendor/eliza/plugins/plugin-anthropic-proxy/src/proxy/stainless-
 * headers.ts (see cc-constants.ts's module doc for the de-vendoring
 * rationale).
 *
 * Real Claude Code sends these on every request via the official Anthropic
 * TypeScript SDK (which is itself generated by Stainless — hence the
 * `x-stainless-*` headers every Stainless-generated SDK emits).
 *
 * SOURCE: `x-stainless-package-version` is the Anthropic SDK's own package
 * version, not Claude Code's. TO UPDATE: check the `@anthropic-ai/sdk`
 * version Claude Code currently bundles (inspect a genuine CC request's
 * `x-stainless-package-version` header, or the SDK version pinned in
 * Claude Code's own `package.json` if available).
 */

import { randomUUID } from 'node:crypto';
import { CC_VERSION } from './cc-constants';

// Generated once per process — mirrors the vendored pipeline's
// per-process INSTANCE_SESSION_ID.
const INSTANCE_SESSION_ID = randomUUID();

export function getStainlessHeaders(): Record<string, string> {
  const p = process.platform;
  const osName = p === 'darwin' ? 'macOS' : p === 'win32' ? 'Windows' : p === 'linux' ? 'Linux' : p;
  const arch = process.arch === 'x64' ? 'x64' : process.arch === 'arm64' ? 'arm64' : process.arch;
  return {
    'user-agent': `claude-cli/${CC_VERSION} (external, cli)`,
    'x-app': 'cli',
    'x-claude-code-session-id': INSTANCE_SESSION_ID,
    'x-stainless-arch': arch,
    'x-stainless-lang': 'js',
    'x-stainless-os': osName,
    'x-stainless-package-version': '0.81.0',
    'x-stainless-runtime': 'node',
    'x-stainless-runtime-version': process.version,
    'x-stainless-retry-count': '0',
    'x-stainless-timeout': '600',
    'anthropic-dangerous-direct-browser-access': 'true',
  };
}
