import { pgTable, serial, text, real, bigint, integer, index } from 'drizzle-orm/pg-core';

export const requestUsage = pgTable(
  'request_usage',
  {
    id: serial('id').primaryKey(),
    requestId: text('request_id').notNull().unique(),
    date: text('date').notNull(),
    sourceIp: text('source_ip'),
    apiKey: text('api_key'),
    attribution: text('attribution'),
    incomingApiType: text('incoming_api_type'),
    provider: text('provider'),
    attemptCount: integer('attempt_count').notNull().default(1),
    incomingModelAlias: text('incoming_model_alias'),
    canonicalModelName: text('canonical_model_name'),
    selectedModelName: text('selected_model_name'),
    finalAttemptProvider: text('final_attempt_provider'),
    finalAttemptModel: text('final_attempt_model'),
    allAttemptedProviders: text('all_attempted_providers'),
    outgoingApiType: text('outgoing_api_type'),
    tokensInput: integer('tokens_input'),
    tokensOutput: integer('tokens_output'),
    tokensReasoning: integer('tokens_reasoning'),
    tokensCached: integer('tokens_cached'),
    tokensCacheWrite: integer('tokens_cache_write'),
    costInput: real('cost_input'),
    costOutput: real('cost_output'),
    costCached: real('cost_cached'),
    costCacheWrite: real('cost_cache_write'),
    costTotal: real('cost_total'),
    costSource: text('cost_source'),
    costMetadata: text('cost_metadata'),
    startTime: bigint('start_time', { mode: 'number' }).notNull(),
    durationMs: bigint('duration_ms', { mode: 'number' }),
    ttftMs: real('ttft_ms'),
    tokensPerSec: real('tokens_per_sec'),
    isStreamed: integer('is_streamed').notNull().default(0),
    isPassthrough: integer('is_passthrough').notNull().default(0),
    responseStatus: text('response_status'),
    tokensEstimated: integer('tokens_estimated').notNull().default(0),
    createdAt: bigint('created_at', { mode: 'number' }).notNull(),
    // Request metadata
    toolsDefined: integer('tools_defined'),
    messageCount: integer('message_count'),
    parallelToolCallsEnabled: integer('parallel_tool_calls_enabled'),
    // Response metadata
    toolCallsCount: integer('tool_calls_count'),
    finishReason: text('finish_reason'),
    // Vision Fallthrough metadata
    isVisionFallthrough: integer('is_vision_fallthrough').notNull().default(0),
    isDescriptorRequest: integer('is_descriptor_request').notNull().default(0),
    // Energy estimation
    kwhUsed: real('kwh_used'),
  },
  (table) => ({
    dateIdx: index('idx_request_usage_date').on(table.date),
    providerIdx: index('idx_request_usage_provider').on(table.provider),
    requestIdIdx: index('idx_request_usage_request_id').on(table.requestId),
  })
);
